// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCmAIbXziWYzNcuKXZPuHKJI_mcKb3RCk',
    appId: '1:771096196846:web:31a2b9d3b0310b0e3465ff',
    messagingSenderId: '771096196846',
    projectId: 'taskmanagement-fc72c',
    authDomain: 'taskmanagement-fc72c.firebaseapp.com',
    storageBucket: 'taskmanagement-fc72c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5RS3EZcxBNis9-20Sj4tGDQZsjoIxE-0',
    appId: '1:771096196846:android:2f36b11d137969253465ff',
    messagingSenderId: '771096196846',
    projectId: 'taskmanagement-fc72c',
    storageBucket: 'taskmanagement-fc72c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjvbePcqvN8Ni0jKv2VWsD6SyrUyk83fo',
    appId: '1:771096196846:ios:37091282e919c25c3465ff',
    messagingSenderId: '771096196846',
    projectId: 'taskmanagement-fc72c',
    storageBucket: 'taskmanagement-fc72c.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjvbePcqvN8Ni0jKv2VWsD6SyrUyk83fo',
    appId: '1:771096196846:ios:37091282e919c25c3465ff',
    messagingSenderId: '771096196846',
    projectId: 'taskmanagement-fc72c',
    storageBucket: 'taskmanagement-fc72c.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCmAIbXziWYzNcuKXZPuHKJI_mcKb3RCk',
    appId: '1:771096196846:web:952d4b31f1de22653465ff',
    messagingSenderId: '771096196846',
    projectId: 'taskmanagement-fc72c',
    authDomain: 'taskmanagement-fc72c.firebaseapp.com',
    storageBucket: 'taskmanagement-fc72c.firebasestorage.app',
  );
}
